from base64 import b64decode as utor

# les petits curieux feraient mieux de suivre le TP...

exec(utor("ZnJvbSBtYXRoIGltcG9ydCBleHAsIHBvdwoKIyBwYXJhbWV0cmVzIGRlIGxhIEdhdXNzaWVubmUKCmEgPSAxICAgICMgb3Jkb25uZWUgZHUgbWF4CmIgPSAyLzMgICMgYWJzY2lzc2UgZHUgbWF4CmMgPSAwLjUgICMgZWNhcnQgdHlwZQoKIyBsYSBHYXVzc2llbm5lCgpkZWYgZih4KToKICAgIHJldHVybiBhICogZXhwKC1wb3coeC1iLDIpLygyKnBvdyhjLCAyKSkpCgojIHNhIGRlcml2ZWUKCmRlZiBmX3ByaW1lKHgpOgogICAgcmV0dXJuIDIgKiAoeC1iKS8oMipwb3coYywgMikpICogZih4KQoKIyBFbmQgT2YgRmlsZQo="))

# End Of File
