-- ==========================
-- fichier : presentation_gestloc.sql
-- base : presentation
-- auteur(s) : LEFRANCOIS Thibaut et RAMAT Pierre
-- date : 17/11/2022
-- role : Créer une présentation pour clarifier l'affichage des tables
-- projet : AGENCE IMMOBILIERE / GESTION LOCATIVE
-- ==========================
SET UNDERLINE ~

COLUMN NOM_AGENCE HEADING "Nom" FORMAT a15 ; 
COLUMN ADR_AGENCE HEADING "Adresse" FORMAT a20 ;
COLUMN TEL_AGENCE HEADING "Telephone" FORMAT a10 ;

COLUMN NOM_LOCATAIRE HEADING "Nom" FORMAT a10 ; 
COLUMN PRE_LOCATAIRE HEADING "Prenom" FORMAT a10 ;
COLUMN TEL_LOCATAIRE HEADING "Telephone" FORMAT a10 ;

COLUMN NOM_PROPRIO HEADING "Nom" FORMAT a10 ; 
COLUMN PRE_PROPRIO HEADING "Prenom" FORMAT a10 ;
COLUMN TEL_PROPRIO HEADING "Telephone" FORMAT a10 ;
COLUMN DEBUT_BAIL HEADING "Nombre de bien" FORMAT 9999 ;

--COLUMN NB_BIEN HEADING "Nombre de bien" FORMAT a10 ;

COLUMN ID_FACTURE_PROPRIO HEADING "Num de facture" FORMAT 99999 ; 
COLUMN TOTAL_GESTION HEADING "Prix de gestion" FORMAT 99999 ;
COLUMN STATUT_GESTION HEADING "Statut" FORMAT a10 ;

COLUMN ADR_BIEN HEADING "Adresse" FORMAT a10 ; 
COLUMN TYPE_BIEN HEADING "Type Bien" FORMAT a13 ;
COLUMN DEBUT_BAIL HEADING "Debut Bail" FORMAT a10 ;
COLUMN FIN_BAIL HEADING "Fin Bail" FORMAT a10 ;
COLUMN STATUT_BIEN HEADING "Statut bien" FORMAT a11 ;

COLUMN ID_FACTURE_LOYER HEADING "Num de facture" FORMAT 99999 ; 
COLUMN TOTAL_CHARGES HEADING "Charges" FORMAT 99999 ;
COLUMN TOTAL_LOYER HEADING "Loyer" FORMAT 99999 ;
COLUMN STATUT_LOYER HEADING "Statut loyer" FORMAT a13 ;



