-- ==========================
-- fichier : dr_gestloc.sql
-- base : gestloc
-- auteur(s) : LEFRANCOIS Thibaut et RAMAT Pierre
-- date : Janvier 2023
-- role : Ordres SQL des dépendances de référence
-- projet : AGENCE IMMOBILIERE / GESTION LOCATIVE
-- resultat dans : dr_gestloc.out (si ce fichier produit une sortie)
-- ==========================

ALTER TABLE PROPRIETAIRE
  ADD CONSTRAINT FK_AGENCE_TO_PROPRIETAIRE
    FOREIGN KEY (ID_AGENCE)
    REFERENCES AGENCE (ID_AGENCE);

ALTER TABLE GESTION
  ADD CONSTRAINT FK_PROPRIETAIRE_TO_GESTION
    FOREIGN KEY (ID_PROPRIO)
    REFERENCES PROPRIETAIRE (ID_PROPRIO);

ALTER TABLE LOCATION
  ADD CONSTRAINT FK_BIEN_TO_LOCATION
    FOREIGN KEY (ID_BIEN)
    REFERENCES BIEN (ID_BIEN);

ALTER TABLE LOCATAIRE
  ADD CONSTRAINT FK_LOCATION_TO_LOCATAIRE
    FOREIGN KEY (ID_LOCATION)
    REFERENCES LOCATION (ID_LOCATION);

ALTER TABLE BIEN
  ADD CONSTRAINT FK_PROPRIETAIRE_TO_BIEN
    FOREIGN KEY (ID_PROPRIO)
    REFERENCES PROPRIETAIRE (ID_PROPRIO);

ALTER TABLE BIEN 
  ADD CONSTRAINT BIEN_CLASS_CHECK CHECK(CLASS_DPE IN('A', 'B', 'C', 'D', 'E', 'F', 'G')) ;