-- ==========================
-- fichier : drop_surgeles.sql
-- base : surgeles
-- auteur(s) : Dupont Achille
-- date : 14/10/22
-- role : role de ce fichier
-- projet : surgelés
-- resultat dans : nom_du_fichier.out (si ce fichier produit une sortie)
-- ==========================

-- DROP TABLE COMMANDE CASCADE CONSTRAINTS;
-- DROP TABLE LIGNE_COMMANDE CASCADE CONSTRAINTS;
-- DROP TABLE PRODUIT CASCADE CONSTRAINTS;
-- DROP TABLE CLIENT CASCADE CONSTRAINTS;
-- DROP TABLE LIVRAISON CASCADE CONSTRAINTS;
-- DROP TABLE LIVREUR CASCADE CONSTRAINTS;


DROP TABLE LIVREUR CASCADE CONSTRAINTS;
DROP TABLE RUCHER  CASCADE CONSTRAINTS;
DROP TABLE RECOLTE CASCADE CONSTRAINTS;
DROP TABLE VELO CASCADE CONSTRAINTS;
DROP TABLE AGENCE CASCADE CONSTRAINTS;
DROP TABLE BIEN CASCADE CONSTRAINTS;
DROP TABLE OEUVRE CASCADE CONSTRAINTS;
DROP TABLE EMPLACEMENT CASCADE CONSTRAINTS;
DROP TABLE SALLE CASCADE CONSTRAINTS;
DROP TABLE VISITEUR CASCADE CONSTRAINTS;
DROP TABLE VISITE CASCADE CONSTRAINTS;
DROP TABLE MUSEE CASCADE CONSTRAINTS;
DROP TABLE VITRINE CASCADE CONSTRAINTS;
DROP TABLE PARCOURS CASCADE CONSTRAINTS;
DROP TABLE ETAPEPAR CASCADE CONSTRAINTS;
DROP TABLE RUCHE CASCADE CONSTRAINTS;
DROP TABLE APICULTEUR CASCADE CONSTRAINTS;
DROP TABLE ADRESSE CASCADE CONSTRAINTS;
DROP TABLE TAILLE_VELO CASCADE CONSTRAINTS;
DROP TABLE TYPE_VELO CASCADE CONSTRAINTS;
DROP TABLE CATEG_VELO CASCADE CONSTRAINTS;
DROP TABLE MARQUE_VELO CASCADE CONSTRAINTS;
DROP TABLE DETAIL_VELO CASCADE CONSTRAINTS;
DROP TABLE FACTURE CASCADE CONSTRAINTS;
DROP TABLE OPERATION CASCADE CONSTRAINTS;
DROP TABLE REGLEMENT CASCADE CONSTRAINTS;
DROP TABLE REPARATEUR CASCADE CONSTRAINTS;
DROP TABLE ARTISTE CASCADE CONSTRAINTS;