DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE COMMANDE CASCADE CONSTRAINTS;
DROP TABLE LIGNE_COMMANDE CASCADE CONSTRAINTS;
DROP TABLE LIVRAISON CASCADE CONSTRAINTS;
DROP TABLE LIVREUR CASCADE CONSTRAINTS;
DROP TABLE PRODUIT CASCADE CONSTRAINTS;