-- ==========================
-- fichier : dr_api.sql
-- base : apiculture
-- auteur(s) : LEFRANCOIS Thibaut
-- date : 29/12/22
-- role : Ordres SQL des dépendances de référence
-- projet : APICULTURE
-- ==========================

ALTER TABLE APICULTEUR ADD CONSTRAINT UQ_APICULTEUR UNIQUE (NOMAPI, PRENOMAPI, MAILAPI) ;

ALTER TABLE APICULTEUR ADD CONSTRAINT PK_APICULTEUR PRIMARY KEY (IDAPI) ;

ALTER TABLE RUCHER ADD CONSTRAINT PK_RUCHER PRIMARY KEY (IDRUCHER) ;

ALTER TABLE RUCHE ADD CONSTRAINT PK_RUCHE PRIMARY KEY (IDRU) ;
ALTER TABLE RUCHE ADD CONSTRAINT FK_APICULTEUR_TO_RUCHE FOREIGN KEY (IDAPI) REFERENCES APICULTEUR (IDAPI) ;
ALTER TABLE RUCHE ADD CONSTRAINT FK_RUCHER_TO_RUCHE FOREIGN KEY (IDRUCHER) REFERENCES RUCHER (IDRUCHER) ;


ALTER TABLE RECOLTE ADD CONSTRAINT PK_RECOLTE PRIMARY KEY (IDRU, DATEREC) ;
ALTER TABLE RECOLTE ADD CONSTRAINT FK_RUCHE_TO_RECOLTE FOREIGN KEY (IDRU) REFERENCES RUCHE (IDRU) ;