ALTER TABLE COMMANDE
  ADD CONSTRAINT FK_CLIENT_TO_COMMANDE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENT (IDCLI);

ALTER TABLE LIGNE_COMMANDE
  ADD CONSTRAINT FK_PRODUIT_TO_LIGNE_COMMANDE
    FOREIGN KEY (IDPRO)
    REFERENCES PRODUIT (IDPRO);

ALTER TABLE LIGNE_COMMANDE
  ADD CONSTRAINT FK_COMMANDE_TO_LIGNE_COMMANDE
    FOREIGN KEY (IDCOM)
    REFERENCES COMMANDE (IDCOM);

ALTER TABLE LIVRAISON
  ADD CONSTRAINT FK_LIVREUR_TO_LIVRAISON
    FOREIGN KEY (IDLIV)
    REFERENCES LIVREUR (IDLIV);

ALTER TABLE LIVRAISON
  ADD CONSTRAINT FK_COMMANDE_TO_LIVRAISON
    FOREIGN KEY (IDCOM)
    REFERENCES COMMANDE (IDCOM);
