-- ================================================
-- Fichier : /h2r-bdd/h2r-delete.sql
-- Base : H2R
-- Auteurs : Demouge Colin & LEFRANCOIS Thibaut D2
-- Date : 27/03/2023
-- Rôle : Définition des dépendances de références de la base de données
-- Projet : SAE2.04 - Exploitation d'une base de données - Gestion Hotels
-- ================================================