-- ================================================
-- Fichier : /h2r-bdd/h2r-ddl-modif.sql
-- Base : H2R
-- Auteurs : Demouge Colin & LEFRANCOIS Thibaut D2
-- Date : 27/03/2023
-- Rôle : Modification des tables concernées par les séquences
-- Projet : SAE2.04 - Exploitation d'une base de données - Gestion Hotels
-- ================================================

ALTER TABLE CUSTOMER_ADDRESS MODIFY
ID_CUSTOMER_ADDRESS DEFAULT SEQ_CUSTOMER_ADDRESS.NEXTVAL;

ALTER TABLE CUSTOMER MODIFY
ID_CUSTOMER DEFAULT SEQ_CUSTOMER.NEXTVAL;

ALTER TABLE BOOKING MODIFY
ID_BOOKING DEFAULT SEQ_BOOKING.NEXTVAL;

ALTER TABLE ROOM_TYPE MODIFY
ID_ROOM_TYPE DEFAULT SEQ_ROOM_TYPE.NEXTVAL;

ALTER TABLE ROOM MODIFY
ID_ROOM DEFAULT SEQ_ROOM.NEXTVAL;

ALTER TABLE HOTEL_ADDRESS MODIFY
ID_HOTEL_ADDRESS DEFAULT SEQ_HOTEL_ADDRESS.NEXTVAL;

ALTER TABLE HOTEL MODIFY
ID_HOTEL DEFAULT SEQ_HOTEL.NEXTVAL;

