-- ==========================
-- fichier : ddl_gestloc.sql
-- base : gestloc
-- auteur(s) : LEFRANCOIS Thibaut et RAMAT Pierre
-- date : 17/11/22
-- role : Ordres SQL de créationde tables
-- projet : AGENCE IMMOBILIERE / GESTION LOCATIVE
-- resultat dans : ddl_gestloc.out (si ce fichier produit une sortie)
-- ==========================

CREATE TABLE AGENCE
(
  ID_AGENCE  NUMBER(4)     NOT NULL,
  NOM_AGENCE VARCHAR2(50)  NOT NULL,
  ADR_AGENCE VARCHAR2(200),
  TEL_AGENCE VARCHAR2(20) ,
  CONSTRAINT PK_AGENCE PRIMARY KEY (ID_AGENCE)
);

--COMMENT ON COLUMN AGENCE.ID_AGENCE IS 'Numéro de l'agence';

--COMMENT ON COLUMN AGENCE.NOM_AGENCE IS 'Nom de l'agence';

--COMMENT ON COLUMN AGENCE.ADR_AGENCE IS 'Adresse de l'agence';

--COMMENT ON COLUMN AGENCE.TEL_AGENCE IS 'Téléphone de l'agence';

CREATE TABLE BIEN
(
  ID_BIEN      NUMBER(3)     NOT NULL,
  ADR_BIEN VARCHAR2(200) NOT NULL,
  TYPE_BIEN    VARCHAR2(20)  NOT NULL,
  DEBUT_BAIL   DATE         ,
  FIN_BAIL     DATE         ,
  STATUT_BIEN  VARCHAR2(20)  NOT NULL,
  ID_PROPRIO   NUMBER(5)     NOT NULL,
  CONSTRAINT PK_BIEN PRIMARY KEY (ID_BIEN)
);

--COMMENT ON COLUMN BIEN.ID_BIEN IS 'Numéro du bien';

--COMMENT ON COLUMN BIEN.ADRESSE_BIEN IS 'Adresse du bien';

--COMMENT ON COLUMN BIEN.TYPE_BIEN IS 'Bien meublé ou non';

--COMMENT ON COLUMN BIEN.DEBUT_BAIL IS 'Date Bail du bien';

--COMMENT ON COLUMN BIEN.FIN_BAIL IS 'Date Bail du bien';

--COMMENT ON COLUMN BIEN.STATUT_BIEN IS 'Bien occupé ou non';

--COMMENT ON COLUMN BIEN.ID_PROPRIO IS 'Numéro du propriétaire';

CREATE TABLE GESTION
(
  ID_GESTION         NUMBER(5)    NOT NULL,
  ID_FACTURE_PROPRIO NUMBER(5)    NOT NULL,
  TOTAL_GESTION      NUMBER(5,2) ,
  STATUT_GESTION     VARCHAR2(20) NOT NULL,
  ID_PROPRIO         NUMBER(5)    NOT NULL,
  CONSTRAINT PK_GESTION PRIMARY KEY (ID_GESTION)
);

--COMMENT ON COLUMN GESTION.ID_GESTION IS 'Numéro de gestion';

--COMMENT ON COLUMN GESTION.ID_FACTURE_PROPRIO IS 'Numéro de facture du propriétaire';

--COMMENT ON COLUMN GESTION.TOTAL_GESTION IS 'Montant de la gestion des biens';

--COMMENT ON COLUMN GESTION.STATUT_GESTION IS 'Gestion payé ou non ';

--COMMENT ON COLUMN GESTION.ID_PROPRIO IS 'Numéro du propriétaire';

CREATE TABLE LOCATAIRE
(
  ID_LOCATAIRE  NUMBER(5)    NOT NULL,
  NOM_LOCATAIRE VARCHAR2(50) NOT NULL,
  PRE_LOCATAIRE VARCHAR2(50),
  TEL_LOCATAIRE VARCHAR2(10) NOT NULL,
  ID_LOCATION   NUMBER(5)    NOT NULL,
  CONSTRAINT PK_LOCATAIRE PRIMARY KEY (ID_LOCATAIRE)
);

--COMMENT ON COLUMN LOCATAIRE.ID_LOCATAIRE IS 'Numéro du locataire';

--COMMENT ON COLUMN LOCATAIRE.NOM_LOCATAIRE IS 'Nom du locataire';

--COMMENT ON COLUMN LOCATAIRE.PRE_LOCATAIRE IS 'Prénom du locataire';

--COMMENT ON COLUMN LOCATAIRE.TEL_LOCATAIRE IS 'Téléphone du locataire';

--COMMENT ON COLUMN LOCATAIRE.ID_LOCATION IS 'Numéro de location';

CREATE TABLE LOCATION
(
  ID_LOCATION      NUMBER(5)    NOT NULL,
  ID_FACTURE_LOYER NUMBER(5)    NOT NULL,
  TOTAL_CHARGES    NUMBER(5,2)  NOT NULL,
  TOTAL_LOYER      NUMBER(6,2) ,
  STATUT_LOYER     VARCHAR2(20) NOT NULL,
  ID_BIEN          NUMBER(3)    NOT NULL,
  CONSTRAINT PK_LOCATION PRIMARY KEY (ID_LOCATION)
);

--COMMENT ON COLUMN LOCATION.ID_LOCATION IS 'Numéro de location';

--COMMENT ON COLUMN LOCATION.ID_FACTURE_LOYER IS 'Numéro de facture du loyer';

--COMMENT ON COLUMN LOCATION.TOTAL_CHARGES IS 'Facture mensuel des charges';

--COMMENT ON COLUMN LOCATION.TOTAL_LOYER IS 'Montant mensuel du loyer';

--COMMENT ON COLUMN LOCATION.STATUT_LOYER IS 'Loyer payé ou non';

--COMMENT ON COLUMN LOCATION.ID_BIEN IS 'Numéro du bien';

CREATE TABLE PROPRIETAIRE
(
  ID_PROPRIO  NUMBER(5)    NOT NULL,
  NOM_PROPRIO VARCHAR2(50) NOT NULL,
  PRE_PROPRIO VARCHAR2(50),
  TEL_PROPRIO VARCHAR2(20) NOT NULL,
  NB_BIEN     NUMBER(2)   ,
  ID_AGENCE   NUMBER(4)    NOT NULL,
  CONSTRAINT PK_PROPRIETAIRE PRIMARY KEY (ID_PROPRIO)
);


--COMMENT ON COLUMN PROPRIETAIRE.ID_PROPRIO IS 'Numéro du propriétaire';

--COMMENT ON COLUMN PROPRIETAIRE.NOM_PROPRIO IS 'Nom du propriétaire';

--COMMENT ON COLUMN PROPRIETAIRE.PRE_PROPRIO IS 'Prénom du propriétaire';

--COMMENT ON COLUMN PROPRIETAIRE.TEL_PROPRIO IS 'Téléphone du propriéataire';

--COMMENT ON COLUMN PROPRIETAIRE.NB_BIEN IS 'Nombre de bien du propriétaire';

--COMMENT ON COLUMN PROPRIETAIRE.ID_AGENCE IS 'Numéro de l'agence';