
II.1) SELECT USER FROM DUAL;

II.2) SELECT BANNER FROM V$VERSION;  

II.3) SELECT NAME, CREATED FROM V$DATABASE;

II.4) SELECT SYSDATE FROM DUAL; 

II.5) ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';
